import WebSocket from 'ws';
const tabs = await (await fetch('http://127.0.0.1:9222/json/list')).json();
const tab = tabs.find(t=>t.type==='page'&&/linear\.app/.test(t.url));
console.log('tab url:', tab?.url);
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise(r=>ws.on('open',r));
let id=0; const send=(m,p)=>new Promise(res=>{const mid=++id;ws.send(JSON.stringify({id:mid,method:m,params:p}));const h=x=>{const d=JSON.parse(x);if(d.id===mid){ws.off('message',h);res(d)}};ws.on('message',h)});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const evalJs=async(expr)=>{const r=await send('Runtime.evaluate',{expression:expr,returnByValue:true,awaitPromise:true});return r.result?.result?.value};
console.log('path:', await evalJs('location.pathname'));
console.log('issue links:', await evalJs(`document.querySelectorAll('a[href*="/issue/"]').length`));
const info = await evalJs(`(()=>{const r=[...document.querySelectorAll('a[href*="/issue/"]')][1];if(!r)return 'none';const b=r.getBoundingClientRect();return JSON.stringify({x:b.x,y:b.y,w:b.width,h:b.height,text:r.textContent.slice(0,50)})})()`);
console.log('row2:', info);
const pt=JSON.parse(info);
const cx = pt.x+400, cy = pt.y+pt.h/2;
await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:cx,y:cy}); await sleep(300);
await send('Input.dispatchMouseEvent',{type:'mousePressed',x:cx,y:cy,button:'right',clickCount:1});
await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:cx,y:cy,button:'right',clickCount:1});
await sleep(1000);
console.log('menus:', await evalJs(`(()=>{const m=[...document.querySelectorAll('[role="menu"],[role="listbox"],[data-radix-popper-content-wrapper]')];return JSON.stringify(m.map(x=>({role:x.getAttribute('role'),items:x.querySelectorAll('[role="menuitem"],[role="option"]').length,txt:x.textContent.slice(0,80)})))})()`));
ws.close();
